const interopDefault = r => r.default || r || [];
const styles = {
  "node_modules/nuxt/dist/app/entry.js": () => import('./_nuxt/entry-styles.QdSowOQ8.mjs').then(interopDefault),
  "pages/Apropos.vue": () => import('./_nuxt/Apropos-styles.D-MGcxqa.mjs').then(interopDefault),
  "pages/index.vue": () => import('./_nuxt/index-styles.s7vDYM8W.mjs').then(interopDefault),
  "pages/Productions/Design.vue": () => import('./_nuxt/Design-styles.D4MyjoaY.mjs').then(interopDefault),
  "pages/Contact.vue": () => import('./_nuxt/Contact-styles.DLk-Il-a.mjs').then(interopDefault),
  "pages/Productions/index.vue": () => import('./_nuxt/index-styles.BmmcJdb-.mjs').then(interopDefault),
  "pages/Productions/Design.vue?vue&type=style&index=0&scoped=9678d372&lang.css": () => import('./_nuxt/Design-styles.D4MyjoaY.mjs').then(interopDefault),
  "pages/Productions/musique.vue": () => import('./_nuxt/musique-styles.Dfxaszq8.mjs').then(interopDefault),
  "pages/Contact.vue?vue&type=style&index=0&scoped=cb1fafed&lang.css": () => import('./_nuxt/Contact-styles.DLk-Il-a.mjs').then(interopDefault),
  "pages/Retouches.vue": () => import('./_nuxt/Retouches-styles.DFIwtZQr.mjs').then(interopDefault),
  "pages/Productions/index.vue?vue&type=style&index=0&scoped=abf03acb&lang.css": () => import('./_nuxt/index-styles.BmmcJdb-.mjs').then(interopDefault),
  "pages/Services.vue": () => import('./_nuxt/Services-styles.C8ivXKxM.mjs').then(interopDefault),
  "pages/Productions/musique.vue?vue&type=style&index=0&scoped=7a19053d&lang.css": () => import('./_nuxt/musique-styles.Dfxaszq8.mjs').then(interopDefault),
  "pages/Services.vue?vue&type=style&index=0&scoped=865e6bb7&lang.css": () => import('./_nuxt/Services-styles.C8ivXKxM.mjs').then(interopDefault),
  "node_modules/@nuxt/ui-templates/dist/templates/error-404.vue": () => import('./_nuxt/error-404-styles.EqvOXghD.mjs').then(interopDefault),
  "node_modules/@nuxt/ui-templates/dist/templates/error-500.vue": () => import('./_nuxt/error-500-styles.xLseMO55.mjs').then(interopDefault),
  "node_modules/@nuxt/ui-templates/dist/templates/error-404.vue?vue&type=style&index=0&scoped=8f77f193&lang.css": () => import('./_nuxt/error-404-styles.EqvOXghD.mjs').then(interopDefault),
  "node_modules/@nuxt/ui-templates/dist/templates/error-500.vue?vue&type=style&index=0&scoped=0b29f077&lang.css": () => import('./_nuxt/error-500-styles.xLseMO55.mjs').then(interopDefault),
  "components/GroupeImgAccueil.vue": () => import('./_nuxt/GroupeImgAccueil-styles.BSWgHAW2.mjs').then(interopDefault),
  "components/AllProjects.vue": () => import('./_nuxt/AllProjects-styles.BFpRpFw9.mjs').then(interopDefault),
  "components/AllServices.vue": () => import('./_nuxt/AllServices-styles.Da3pIHu-.mjs').then(interopDefault),
  "components/AllProjects.vue?vue&type=style&index=0&scoped=aae280f3&lang.css": () => import('./_nuxt/AllProjects-styles.BFpRpFw9.mjs').then(interopDefault),
  "components/AllServices.vue?vue&type=style&index=0&scoped=ff595d5f&lang.css": () => import('./_nuxt/AllServices-styles.Da3pIHu-.mjs').then(interopDefault),
  "components/Carousel.vue": () => import('./_nuxt/Carousel-styles.DevoW8Hk.mjs').then(interopDefault),
  "pages/Apropos.vue?vue&type=style&index=0&scoped=b86e0211&lang.css": () => import('./_nuxt/Apropos-styles.D-MGcxqa.mjs').then(interopDefault),
  "components/CardServices.vue": () => import('./_nuxt/CardServices-styles.wxmsMIsx.mjs').then(interopDefault),
  "pages/Retouches.vue?vue&type=style&index=0&scoped=9c960113&lang.css": () => import('./_nuxt/Retouches-styles.DFIwtZQr.mjs').then(interopDefault),
  "pages/index.vue?vue&type=style&index=0&lang.css": () => import('./_nuxt/index-styles.s7vDYM8W.mjs').then(interopDefault),
  "components/CardServices.vue?vue&type=style&index=0&scoped=750117d9&lang.css": () => import('./_nuxt/CardServices-styles.wxmsMIsx.mjs').then(interopDefault),
  "layouts/default.vue": () => import('./_nuxt/default-styles.gyFXxQ6F.mjs').then(interopDefault),
  "components/GroupeImgAccueil.vue?vue&type=style&index=0&scoped=45193003&lang.css": () => import('./_nuxt/GroupeImgAccueil-styles.BSWgHAW2.mjs').then(interopDefault),
  "layouts/default.vue?vue&type=style&index=0&lang.css": () => import('./_nuxt/default-styles.gyFXxQ6F.mjs').then(interopDefault),
  "components/Carousel.vue?vue&type=style&index=0&scoped=39b47dae&lang.css": () => import('./_nuxt/Carousel-styles.DevoW8Hk.mjs').then(interopDefault),
  "components/Navbar.vue": () => import('./_nuxt/Navbar-styles.Dlrhjwr6.mjs').then(interopDefault),
  "components/Footer.vue": () => import('./_nuxt/Footer-styles.BXDNkv2P.mjs').then(interopDefault),
  "components/Navbar.vue?vue&type=style&index=0&scoped=ea01ea4f&lang.css": () => import('./_nuxt/Navbar-styles.Dlrhjwr6.mjs').then(interopDefault),
  "components/Footer.vue?vue&type=style&index=0&scoped=20d8a321&lang.css": () => import('./_nuxt/Footer-styles.BXDNkv2P.mjs').then(interopDefault)
};

export { styles as default };
//# sourceMappingURL=styles.mjs.map
